# Generated by Django 5.0.7 on 2024-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuta_travel', '0002_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_ad',
            field=models.EmailField(max_length=255),
        ),
    ]
