# Generated by Django 5.0.7 on 2024-07-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuta_travel', '0003_alter_mail_mail_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_id',
            new_name='login_pw_check',
        ),
    ]
