# Generated by Django 5.0.7 on 2024-07-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuta_travel', '0004_rename_login_id_post_login_pw_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='SendMail',
        ),
        migrations.RenameField(
            model_name='sendmail',
            old_name='mail_ad',
            new_name='mail_send',
        ),
    ]
